### ISSUE TITLE
Pillow is now 11.0 - can't install photos because wheel throws error

### ISSUE THREAD

**Issue by SirLaffalot** [pelican-plugins/photos#126]
See problem below. I'm running Archlinux up to date which wants Pillow 11.0
Wheel fails because photos wants Pillow 10

Only way I could install photos, was to edit the yaml file - change the ~=10 to >=10
...
dependencies = [
    "pelican>=4.5",
    "beautifulsoup4~=4.12.2",
    "piexif~=1.1.3",
    "Pillow>=10.0.1",
]
...

          pip install Pillow
Collecting Pillow
  Downloading pillow-11.0.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Downloading pillow-11.0.0-cp313-cp313-manylinux_2_28_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 27.4 MB/s eta 0:00:00
Installing collected packages: Pillow
Successfully installed Pillow-11.0.0

(venv) [ivan@radagast Another-try]$ pip install pelican-photos
Collecting pelican-photos
  Using cached pelican_photos-1.6.0-py3-none-any.whl.metadata (16 kB)
Collecting pelican>=4.5 (from pelican-photos)
  Using cached pelican-4.10.2-py3-none-any.whl.metadata (5.4 kB)
Collecting beautifulsoup4~=4.12.2 (from pelican-photos)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting piexif~=1.1.3 (from pelican-photos)
  Using cached piexif-1.1.3-py2.py3-none-any.whl.metadata (3.7 kB)
Collecting Pillow~=10.0.1 (from pelican-photos)
  Using cached Pillow-10.0.1.tar.gz (50.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/ivan/workspace/TakeABow/Another-try/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/ivan/workspace/TakeABow/Another-try/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/ivan/workspace/TakeABow/Another-try/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-3bsadtz5/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-3bsadtz5/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-3bsadtz5/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 30, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by SirLaffalot** [comment]
git diff output...

diff --git a/pyproject.toml b/pyproject.toml
index 9c7cf9b..045ae9c 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -31,7 +31,7 @@ dependencies = [
     "pelican>=4.5",
     "beautifulsoup4~=4.12.2",
     "piexif~=1.1.3",
-    "Pillow~=10.0.1",
+    "Pillow>=10.0.1",
 ]
 
 [project.urls]

**Comment by b00bl1k** [comment]
Pillow 10.0.1 does not support python 3.13 https://github.com/python-pillow/Pillow/issues/8075

**Comment by phibos** [comment]
A new patch version has been released a few minutes ago and works with pillow < 12.0 Feel free to test.
